### PR TITLE
Add mentorship input into mentoring-request

### LINKED ISSUE #20: Improve the mentoring form
We need in the request mentoring, a field where the applicant can add what he expects from the mentorship. and which mentor you would be comfortable with, it is also possible that the mentoring applicant has chosen the mentor by clicking next to his photo on the OpenScienceLabs website, but that does not appear on the form. It would also be good to include in the form the availability of schedule, to specify a first meeting.

### PR DESCRIPTION
**Pull request by luabida**
fix #20 partially

### CODE REVIEW

**Comment by luabida** [comment]
@xmnlab about:
> We need in the request mentoring, a field where the applicant can add what he expects from the mentorship

I can insert this into this PR if you like. Please lmk if you did it already, otherwise I can easily add it here

**Comment by xmnlab** [comment]
Go ahead please. Thank you so much

**Comment by luabida** [comment]
@xmnlab listo

**Review by xmnlab — APPROVED** [review]
LGTM. thanks!

**Pull request merged**
